# Generated by Django 3.2.18 on 2023-04-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpisokBiletov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('name_out', models.CharField(max_length=256)),
                ('name_in', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(max_length=256)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
    ]
