# Generated by Django 3.2.18 on 2023-04-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spisok_biletov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiletiImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csv_old/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
