# Generated by Django 3.2.18 on 2023-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spisok_biletov', '0002_biletiimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisokbiletov',
            name='short_description',
            field=models.CharField(max_length=512),
        ),
    ]
