# Generated by Django 3.2.18 on 2023-04-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spisok_biletov', '0003_alter_spisokbiletov_short_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiletiImport',
        ),
    ]
