# Generated by Django 3.2.18 on 2023-05-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spisok_biletov', '0004_delete_biletiimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisokbiletov',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
