# Generated by Django 3.2.18 on 2023-05-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spisok_biletov', '0005_alter_spisokbiletov_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisokbiletov',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
